common: &common
  consumer_key: '<consumer_key>'
  consumer_secret: '<consumer_secret>'
  access_token: '<access_token>'
  access_token_secret: '<access_token_secret>'

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common