common: &common
  consumer_key: '3B0Cg3sf5C50GQQ6IyDeQQ'
  consumer_secret: '4R6ZVjeE3T1B69ZsbrbBhn42KVGek0KRZm6yjDlRrY'
  access_token: '127274227-b77OaV9AITfMGZFDhsIiFBTKeTDLpsSpJt7KeB4'
  access_token_secret: 'pQGOLhwl4QKKCgfWq987hLs0T9pbQtl2jhMq144a4'

test:
  <<: *common

development:
  <<: *common

production:
  <<: *common